name: Publish Library

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://npm.pkg.github.com

    - name: Install Dependencies
      run: npm ci

    - name: Build Library
      run: ng build fractal-library --configuration production

    - name: Publish to GitHub Packages
      run: |
        cd dist/fractal-library
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
