name: Publish Library

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@4.1.1

    - name: Setup Node.js
      uses: actions/setup-node@4.0.0
      with:
        node-version: 20
        registry-url: https://npm.pkg.github.com
        scope: '@mfernandez69'   # Añadido scope para autenticación correcta

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install Dependencies
      run: npm ci

    - name: Build Library
      run: npm run build:library

    - name: Increment Version and Publish
      run: |
        cd dist/fractal-library
        npm version patch --no-git-tag-version
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
